// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		int N = Integer.parseInt(args[0]);
		int count = 1;
		int m = 0;

		while(count < N){
			double random = Math.random();
			if(random > 0.5){
				m = m + 1;
			}
			count = count + 1;
		}

		int less = N - m;
		
		
		System.out.println("> 0.5: " + m + " times");
		System.out.println("<= 0.5: " + less + " times");
		if (m != 0 && less != 0) {
    		if (m > less) {
        		System.out.println("Ratio: " + ((double) less / m));
    			} else {
        			System.out.println("Ratio: " + ((double) m / less));
    				}
				}
		
	}
}
